FROM 4thlabs/java:jdk-8
MAINTAINER 4thlabs <4thlabs@gmail.com>

RUN \
    wget http://download.go.cd/gocd-deb/go-server-15.1.0-1863.deb && \
    dpkg -i go-server-15.1.0-1863.deb && \
    rm go-server-15.1.0-1863.deb